export const DummyData = [
  {
    Product: 'Milk',
    Category: 'Dairy',
    Price: 2.99,
    Description: "Fresh cow's milk.",
  },
  {
    Product: 'Cheese',
    Category: 'Dairy',
    Price: 4.5,
    Description: 'Aged cheddar cheese.',
  },
  {
    Product: 'Eggs',
    Category: 'Dairy',
    Price: 2.0,
    Description: 'Farm-fresh large eggs.',
  },
  {
    Product: 'Yogurt',
    Category: 'Dairy',
    Price: 3.25,
    Description: 'Creamy Greek yogurt.',
  },
  {
    Product: 'Bread',
    Category: 'Grocery',
    Price: 1.99,
    Description: 'Whole wheat sandwich bread.',
  },
  {
    Product: 'Butter',
    Category: 'Dairy',
    Price: 2.75,
    Description: 'Salted creamy butter.',
  },
  {
    Product: 'Apples',
    Category: 'Grocery',
    Price: 0.75,
    Description: 'Crisp red apples.',
  },
  {
    Product: 'Bananas',
    Category: 'Grocery',
    Price: 0.6,
    Description: 'Ripe yellow bananas.',
  },
  {
    Product: 'Spinach',
    Category: 'Grocery',
    Price: 1.5,
    Description: 'Fresh baby spinach leaves.',
  },
  {
    Product: 'Tomatoes',
    Category: 'Grocery',
    Price: 0.9,
    Description: 'Juicy vine-ripened tomatoes.',
  },
  {
    Product: 'Cereal',
    Category: 'Grocery',
    Price: 3.99,
    Description: 'Crunchy whole grain cereal.',
  },
  {
    Product: 'Ice Cream',
    Category: 'Dairy',
    Price: 5.5,
    Description: 'Creamy vanilla ice cream.',
  },
  {
    Product: 'Orange Juice',
    Category: 'Grocery',
    Price: 2.25,
    Description: 'Freshly squeezed orange juice.',
  },
];
