export const DummyData = [
  {
    Product: 'Milk',
    Category: 'Dairy',
    Price: 2.99,
    Description: "Fresh cow's milk ppppppp shhshhsshhshshshshshshshshh.",
    img: require('../../../src/assets/images/milk.jpeg'),
  },
  {
    Product: 'Cheese',
    Category: 'Dairy',
    Price: 4.5,
    Description: 'Aged cheddar cheese.',
    img: require('../../../src/assets/images/cheese.jpeg'),
  },
  {
    Product: 'Eggs',
    Category: 'Dairy',
    Price: 2.0,
    Description: 'Farm-fresh large eggs.',
    img: require('../../../src/assets/images/eggs.jpeg'),
  },

  {
    Product: 'Yogurt',
    Category: 'Dairy',
    Price: 3.25,
    Description: 'Creamy Greek yogurt.',
    img: require('../../../src/assets/images/yogurt.jpeg'),
  },
  {
    Product: 'Bread',
    Category: 'Grocery',
    Price: 1.99,
    Description: 'Whole wheat sandwich bread.',
    img: require('../../../src/assets/images/bread.jpeg'),
  },
  {
    Product: 'Butter',
    Category: 'Dairy',
    Price: 2.75,
    Description: 'Salted creamy butter.',
    img: require('../../../src/assets/images/butter.jpeg'),
  },
  {
    Product: 'Apples',
    Category: 'Grocery',
    Price: 0.75,
    Description: 'Crisp red apples.',
    img: require('../../../src/assets/images/apples.jpeg'),
  },
  {
    Product: 'Bananas',
    Category: 'Grocery',
    Price: 0.6,
    Description: 'Ripe yellow bananas.',
    img: require('../../../src/assets/images/banana.jpeg'),
  },
  {
    Product: 'Spinach',
    Category: 'Grocery',
    Price: 1.5,
    Description: 'Fresh baby spinach leaves.',
    img: require('../../../src/assets/images/spinach.jpeg'),
  },
  {
    Product: 'Tomatoes',
    Category: 'Grocery',
    Price: 0.9,
    Description: 'Juicy vine-ripened tomatoes.',
    img: require('../../../src/assets/images/tomatoes.jpeg'),
  },
  {
    Product: 'Cereal',
    Category: 'Grocery',
    Price: 3.99,
    Description: 'Crunchy whole grain cereal.',
    img: require('../../../src/assets/images/cereal.jpeg'),
  },
  {
    Product: 'Ice Cream',
    Category: 'Dairy',
    Price: 5.5,
    Description: 'Creamy vanilla ice cream.',
    img: require('../../../src/assets/images/iceCream.jpeg'),
  },

  {
    Product: 'Orange Juice',
    Category: 'Grocery',
    Price: 2.25,
    Description: 'Freshly squeezed orange juice.',
    img: require('../../../src/assets/images/orangeJuice.jpeg'),
  },
];
