export const DummyData = [
  {
    Product: 'Milk',
    Category: 'Dairy',
    Quantity: 1,
    Price: 22,
    Description: "Fresh cow's milk.",
    img: require('../../../src/assets/images/milk.jpeg'),
  },
  {
    Product: 'Cheese',
    Category: 'Dairy',
    Quantity: 1,
    Price: 20,
    Description: 'Aged cheddar cheese.',
    img: require('../../../src/assets/images/cheese.jpeg'),
  },
  {
    Product: 'Eggs',
    Category: 'Dairy',
    Quantity: 1,
    Price: 120,
    Description: 'Farm-fresh large eggs.',
    img: require('../../../src/assets/images/eggs.jpeg'),
  },

  {
    Product: 'Yogurt',
    Category: 'Dairy',
    Quantity: 1,
    Price: 30,
    Description: 'Creamy Greek yogurt.',
    img: require('../../../src/assets/images/yogurt.jpeg'),
  },
  {
    Product: 'Bread',
    Category: 'Grocery',
    Quantity: 1,
    Price: 50,
    Description: 'Whole wheat sandwich bread.',
    img: require('../../../src/assets/images/bread.jpeg'),
  },
  {
    Product: 'Butter',
    Category: 'Dairy',
    Quantity: 1,
    Price: 25,
    Description: 'Salted creamy butter.',
    img: require('../../../src/assets/images/butter.jpeg'),
  },
  {
    Product: 'Apples',
    Category: 'Grocery',
    Quantity: 1,
    Price: 200,
    Description: 'Crisp red apples.',
    img: require('../../../src/assets/images/apples.jpeg'),
  },
  {
    Product: 'Bananas',
    Category: 'Grocery',
    Quantity: 1,
    Price: 150,
    Description: 'Ripe yellow bananas.',
    img: require('../../../src/assets/images/banana.jpeg'),
  },
  {
    Product: 'Spinach',
    Category: 'Grocery',
    Quantity: 1,
    Price: 30,
    Description: 'Fresh baby spinach leaves.',
    img: require('../../../src/assets/images/spinach.jpeg'),
  },
  {
    Product: 'Tomatoes',
    Category: 'Grocery',
    Quantity: 1,
    Price: 25,
    Description: 'Juicy vine-ripened tomatoes.',
    img: require('../../../src/assets/images/tomatoes.jpeg'),
  },
  {
    Product: 'Cereal',
    Category: 'Grocery',
    Quantity: 1,
    Price: 150,
    Description: 'Crunchy whole grain cereal.',
    img: require('../../../src/assets/images/cereal.jpeg'),
  },
  {
    Product: 'Ice Cream',
    Category: 'Dairy',
    Quantity: 1,
    Price: 200,
    Description: 'Creamy vanilla ice cream.',
    img: require('../../../src/assets/images/iceCream.jpeg'),
  },

  {
    Product: 'Orange Juice',
    Category: 'Grocery',
    Quantity: 1,
    Price: 225,
    Description: 'Freshly squeezed orange juice.',
    img: require('../../../src/assets/images/orangeJuice.jpeg'),
  },
];
